FROM python:3.12
ENV VIRTUAL_ENV=/env
ENV PATH=/env/bin:$PATH

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential checkinstall redis-server
RUN python3.12 -m pip install --upgrade pip

# Copy and install the application
WORKDIR /app
COPY . /app
RUN pip install -e .

# Start Redis
RUN service redis-server start

CMD ["bash"]