"""calculate variable usage

Revision ID: 20260508_0002
Revises: 20260508_0001
Create Date: 2026-05-08 20:05:06.418279
"""

from alembic import op
import sqlalchemy as sa


revision = "20260508_0002"
down_revision = "20260508_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculate_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("visit_id", sa.Integer(), nullable=False),
        sa.Column("request_uuid", sa.String(length=36), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=True),
        sa.Column("api_version", sa.String(length=32), nullable=True),
        sa.Column("country_id", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("endpoint", sa.String(length=64), nullable=True),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("content_length_bytes", sa.Integer(), nullable=True),
        sa.Column("response_status_code", sa.Integer(), nullable=True),
        sa.Column("distinct_variable_count", sa.Integer(), nullable=False),
        sa.Column("unsupported_variable_count", sa.Integer(), nullable=False),
        sa.Column(
            "deprecated_allowlisted_variable_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_uuid"),
    )
    with op.batch_alter_table("calculate_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_calculate_requests_client_created",
            ["client_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_calculate_requests_country_created",
            ["country_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_calculate_requests_visit_id", ["visit_id"], unique=False
        )

    op.create_table(
        "calculate_request_variables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("country_id", sa.String(length=16), nullable=False),
        sa.Column("api_version", sa.String(length=32), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("response_status_code", sa.Integer(), nullable=True),
        sa.Column("variable_name", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("period_granularity", sa.String(length=16), nullable=False),
        sa.Column("entity_count", sa.Integer(), nullable=False),
        sa.Column("period_count", sa.Integer(), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("availability_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["calculate_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "request_id",
            "variable_name",
            "entity_type",
            "source",
            name="ux_calc_vars_request_variable_entity_source",
        ),
    )
    with op.batch_alter_table(
        "calculate_request_variables", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_calc_vars_client_variable_created",
            ["client_id", "variable_name", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_calc_vars_country_model_variable",
            ["country_id", "model_version", "variable_name"],
            unique=False,
        )
        batch_op.create_index(
            "ix_calc_vars_variable_created",
            ["variable_name", "created_at"],
            unique=False,
        )

    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.alter_column(
            "client_id", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE visits SET client_id = '' WHERE client_id IS NULL")
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.alter_column(
            "client_id", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    with op.batch_alter_table(
        "calculate_request_variables", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_calc_vars_variable_created")
        batch_op.drop_index("ix_calc_vars_country_model_variable")
        batch_op.drop_index("ix_calc_vars_client_variable_created")

    op.drop_table("calculate_request_variables")
    with op.batch_alter_table("calculate_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_calculate_requests_visit_id")
        batch_op.drop_index("ix_calculate_requests_country_created")
        batch_op.drop_index("ix_calculate_requests_client_created")

    op.drop_table("calculate_requests")
    # ### end Alembic commands ###
