"""support legacy calculate requests

Revision ID: 20260810_0005
Revises: 20260519_0004
Create Date: 2026-08-10 21:03:45.092278
"""

import sqlalchemy as sa
from alembic import op


revision = "20260810_0005"
down_revision = "20260519_0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calculate_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "record_source",
                sa.String(length=16),
                server_default="live",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "variable_metadata_collected",
                sa.Boolean(),
                server_default=sa.true(),
                nullable=False,
            )
        )
        batch_op.alter_column(
            "country_id",
            existing_type=sa.VARCHAR(length=16),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    calculate_requests = sa.table(
        "calculate_requests",
        sa.column("record_source", sa.String(length=16)),
    )
    op.execute(
        calculate_requests.delete().where(
            calculate_requests.c.record_source == "legacy_visits"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calculate_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "country_id",
            existing_type=sa.VARCHAR(length=16),
            nullable=False,
        )
        batch_op.drop_column("variable_metadata_collected")
        batch_op.drop_column("record_source")

    # ### end Alembic commands ###
