"""cap analytics variable names

Downgrade note:
    This migration is not data-preserving for variable names longer than
    250 characters. Those names are capped before storage in this revision,
    so downgrading deletes rows marked as truncated before restoring the old
    per-request uniqueness constraint.

Revision ID: 20260512_0003
Revises: 20260508_0002
Create Date: 2026-05-12 13:42:10.751334
"""

from alembic import op
import sqlalchemy as sa


revision = "20260512_0003"
down_revision = "20260508_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "calculate_request_variables", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "variable_name_truncated",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
        batch_op.drop_constraint(
            batch_op.f("ux_calc_vars_request_variable_entity_source"),
            type_="unique",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    calculate_request_variables = sa.table(
        "calculate_request_variables",
        sa.column("variable_name_truncated", sa.Boolean()),
    )
    op.execute(
        calculate_request_variables.delete().where(
            calculate_request_variables.c.variable_name_truncated.is_(True)
        )
    )

    with op.batch_alter_table(
        "calculate_request_variables", schema=None
    ) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("ux_calc_vars_request_variable_entity_source"),
            ["request_id", "variable_name", "entity_type", "source"],
        )
        batch_op.drop_column("variable_name_truncated")

    # ### end Alembic commands ###
