"""add calculate analytics routing version

Revision ID: 20260519_0004
Revises: 20260512_0003
Create Date: 2026-05-19 22:05:42.821147
"""

from alembic import op
import sqlalchemy as sa


revision = "20260519_0004"
down_revision = "20260512_0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "calculate_request_variables", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("requested_version", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("resolved_channel", sa.String(length=16), nullable=True)
        )
        batch_op.create_index(
            "ix_calc_vars_channel_created",
            ["resolved_channel", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_calc_vars_requested_created",
            ["requested_version", "created_at"],
            unique=False,
        )

    with op.batch_alter_table("calculate_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("requested_version", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("resolved_channel", sa.String(length=16), nullable=True)
        )
        batch_op.create_index(
            "ix_calculate_requests_channel_created",
            ["resolved_channel", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_calculate_requests_requested_created",
            ["requested_version", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calculate_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_calculate_requests_requested_created")
        batch_op.drop_index("ix_calculate_requests_channel_created")
        batch_op.drop_column("resolved_channel")
        batch_op.drop_column("requested_version")

    with op.batch_alter_table(
        "calculate_request_variables", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_calc_vars_requested_created")
        batch_op.drop_index("ix_calc_vars_channel_created")
        batch_op.drop_column("resolved_channel")
        batch_op.drop_column("requested_version")

    # ### end Alembic commands ###
