runtime: custom
env: flex
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 32
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
readiness_check:
  app_start_timeout_sec: 1800  # Maximum allowed (30 minutes)
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 1
liveness_check:
  initial_delay_sec: 300  # Give app time to fully start
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 1
env_variables:
  AUTH0_ADDRESS_NO_DOMAIN: ${AUTH0_ADDRESS_NO_DOMAIN}
  AUTH0_AUDIENCE_NO_DOMAIN: ${AUTH0_AUDIENCE_NO_DOMAIN}
  USER_ANALYTICS_DB_USERNAME: ${USER_ANALYTICS_DB_USERNAME}
  USER_ANALYTICS_DB_PASSWORD: ${USER_ANALYTICS_DB_PASSWORD}
  USER_ANALYTICS_DB_CONNECTION_NAME: ${USER_ANALYTICS_DB_CONNECTION_NAME}
  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
