# DO NOT commit actual production values to the repository

---
app:
  name: policyengine-household-api
  environment: test_with_auth
  debug: true

auth:
  enabled: true
  provider: auth0
  auth0:
    address: ${AUTH0_ADDRESS_NO_DOMAIN}  # From env var
    audience: ${AUTH0_AUDIENCE_NO_DOMAIN}  # From env var
    test_token: ${AUTH0_TEST_TOKEN_NO_DOMAIN}  # From env var

ai:
  enabled: true
  provider: anthropic
  anthropic:
    api_key: ${ANTHROPIC_API_KEY}  # From env var
    model: claude-3-5-sonnet-20240620
    max_tokens: 1500
    temperature: 0.0

server:
  port: 8080
  workers: 2
  timeout: 300
  
logging:
  level: INFO
  format: json
  # Google Cloud Logging auto-configured via environment