name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - upgrade-python-3.13
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./gcp/Dockerfile
          push: true
          tags: |
            ghcr.io/policyengine/policyengine-household-api:python313
            ghcr.io/policyengine/policyengine-household-api:latest
            ghcr.io/policyengine/policyengine-household-api:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/policyengine/policyengine-household-api:buildcache
          cache-to: type=registry,ref=ghcr.io/policyengine/policyengine-household-api:buildcache,mode=max